apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: "{{ .Release.Name }}-deployment-front"
  namespace: {{ .Values.namespace_app1 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: "{{ .Values.image.repositoryfront }}:{{ .Values.image.tagfront }}"
        imagePullPolicy: IfNotPresent
        name: front
        env:
          - name: HOST_BACK
            value: back:8080
