apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service-front"
  namespace: {{ .Values.namespace_app1 }}
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: front
  type: ClusterIP