apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ntw2
spec:
  podSelector: 
    matchLabels:
      app: nginx
  policyTypes:
  - Egress      
  egress: 
  - to:
    - podSelector:
        matchLabels:
          app: nginx2
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  - to:               
    ports:            
    - protocol: UDP  
      port: 53
