apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-back
  name: front-back
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
        - image: nginx:1.20
          imagePullPolicy: IfNotPresent
          name: front
          volumeMounts:
            - mountPath: "/static"
              name: nfc-volume
        - image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          name: back
          volumeMounts:
            - mountPath: "/static"
              name: nfc-volume
          env:
            - name: HTTP_PORT
              value: "8080"
      volumes:
        - name: nfc-volume
          persistentVolumeClaim:
            claimName: nfc-pvc