apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service-front"
  namespace: {{ .Values.namespace_app1 }}
spec:
  ports:
    - name: web
      port: 443
      targetPort: 443
      nodePort: 30000
  selector:
    app: front
  type: NodePort