replicaCount: 1

namespace_app1: app1
namespace_app2: app2

image:
  repositoryfront: nginx
  repositoryback: praqma/network-multitool
  # Overrides the image tag whose default is the chart appVersion.
  tagfront: 1.23.2
  tagback: alpine-extra
resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

appPort: 80
